[workspace]

members = [
  "russell_lab",
  "russell_nonlin",
  "russell_ode",
  "russell_pde",
  "russell_sparse",
  "russell_stat",
  "russell_tensor",
]

resolver = "2"

[workspace.lints.clippy]
approx_constant = "allow"        # allow large constants; e.g. for OEIS reference
bool_assert_comparison = "allow" # allow "assert_eq!(x, true)" for better diagnostics
collapsible_if = "allow"         # allow nested "if" for readability
excessive_precision = "allow"    # allow large constants; e.g. for OEIS reference
identity_op = "allow"            # allow "i + 0" for uniform unrolled loops
let_unit_value = "allow"         # allow "let _ = CONST;" to force const evaluation
manual_is_multiple_of = "allow"  # allow "n % k == 0" instead of is_multiple_of()
manual_range_contains = "allow"  # allow if "a < b && c < d" constructions
needless_range_loop = "allow"    # allow "for i in a..b" instead of range
new_without_default = "allow"    # The user is encouraged to call new()
type_complexity = "allow"        # allow deeply nested array types (index maps)

[profile.release]
lto = true
codegen-units = 1
