FROM archlinux:base-devel

# initialize
RUN pacman -Sy go git --noconfirm

# set user
RUN useradd -G wheel -m user
RUN echo "user ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
RUN chown -R user:wheel /usr/local/src/
USER user
WORKDIR /usr/local/src/

# install rust and dependencies
RUN sudo pacman -S rust blas-openblas suitesparse

# copy files
COPY --chown=user:user . russell
WORKDIR russell

# run tests
RUN cargo test
