[package]
name = "russell_tensor"
version = "3.3.0"
edition = "2024"
license = "MIT"
description = "Tensor analysis, calculus, and functions for continuum mechanics"
homepage = "https://github.com/cpmech/russell"
repository = "https://github.com/cpmech/russell"
documentation = "https://docs.rs/russell_tensor"
readme = "README.md"
categories = ["mathematics", "science"]
keywords = ["tensor", "continuum", "mechanics"]

[features]
intel_mkl = ["russell_lab/intel_mkl"]

[dependencies]
russell_lab = { path = "../russell_lab", version = "3" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
criterion = "0.8"

[[bench]]
name = "polar_decomp_benchmark"
harness = false
path = "benchmarks/polar_decomp_benchmark.rs"

[[bench]]
name = "eigen_values_benchmark"
harness = false
path = "benchmarks/eigen_values_benchmark.rs"

[lints]
workspace = true
