name: macOS
on: [pull_request]
jobs:
  macos:
    runs-on: macos-latest
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v4
      - name: Configure environment
        run: |
          echo TMPDIR=/tmp | tee -a $GITHUB_ENV
          env
      - name: Install Libraries
        run: |
          brew install lapack openblas suite-sparse
      - name: Run tests
        run: |
          cargo test
