name: Test on Arch Linux
on: [pull_request]
jobs:
  test_on_arch_linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - intel_mkl: ""
            local_sparse: ""
            label: option1_default
          - intel_mkl: ""
            local_sparse: "1"
            label: option2_openblas_local
          - intel_mkl: "1"
            local_sparse: "1"
            label: option3_mkl_local
    name: test (${{ matrix.label }})
    steps:
      - uses: actions/checkout@v4
      - name: Build docker image (${{ matrix.label }})
        run: |
          bash zscripts/docker-build-arch.bash ${{ matrix.intel_mkl }} ${{ matrix.local_sparse }}
